version: "3.7"
services:
  api_service:
    build: .
    ports:
      - "9000:9000"
    environment:
      - "spring.datasource.url=jdbc:mysql://mysql_db:3306/daily_view"
      - "spring.redis.host=redis"
    depends_on:
      - mysql_db
      - redis
    links:
      - mysql_db
      - redis
  mysql_db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: daily_view
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"

